### ISSUE TITLE
Update merch store schema to optimize single "option group" items

### ISSUE THREAD

**Issue by shravanhariharan2** [acmucsd/membership-portal#185]
The item option requirement has been eased to support only 1 "option group" (e.g. size, color, shape, etc) per item. A design shown below (courtesy of @steets250) reflects this change:

![image](https://user-images.githubusercontent.com/33337209/118070510-e6783c00-b35a-11eb-80a9-2fa6e7432bed.png)

Additionally, merch collection titles support text colors, which can be customized and would need to be stored in the backend:

![image](https://user-images.githubusercontent.com/33337209/118070715-4373f200-b35b-11eb-945c-88a622127059.png)

The following schema changes have been planned:
```ts
interface MerchandiseCollectionModel {
  uuid: Uuid;
  title: string;
  titleTextColor: string; // hex color used for the title text (each collection title has its own text color)
  description: string;
  archived: boolean;
  items: MerchandiseItemModel[];
}

interface MerchandiseItemModel {
  uuid: Uuid;
  itemName: string;
  collection: MerchandiseCollectionModel;
  picture: string;
  description: string;
  monthlyLimit: number;
  lifetimeLimit: number;
  hidden: boolean;
  option/optionGroup/optionCategory: string | null; // exact name TBD, but is title of options, (e.g. the string "size", the string "color"; null if no options (since we only have 1 option per item)
  options: MerchandiseItemOptionModel[];
}

interface MerchandiseItemOptionModel {
  uuid: Uuid;
  item: MerchandiseItemModel;
  quantity: number;
  price: number;
  discountPercentage: number;
  value: string; // the option value, e.g. 'S', 'M', 'L' if this.item.optionGroup === 'size'
  position: number; // 0, 1, 2, etc. (for determining sort order of displaying options on frontend, i.e. XS (0) < S (1) < M (2) < L (3)< XL (4)etc)
  orders: OrderItemModel[];
}
```

**Comment by shravanhariharan2** [comment]
@sumeet-bansal following up on our Discord discussion - I've added some more context, comments, and better-named variables from what was previously on Notion, let me know if that clears up any of your questions

**Comment by shravanhariharan2** [comment]
Also, if anyone has a better name for "option groups" let me know. Nomenclature is hard  ¯\_(ツ)_/¯

**Comment by sumeet-bansal** [comment]
Ok I see, so schema changes:
1. merch collection has a color associated with it
2. merch item has an option type
3. merch item option has a value and a position

For (1), having a color for a merch collection seems like a FE metadata thing; could this just be some JSON mapping in the FE since it has to do with displaying data and is purely cosmetic? I'm not against keeping it in the BE but it really seems like a cosmetic display thing which's why I don't think it really belongs with the kind of data we want to store in the database.

For (2) and (3), why not use the current schema? Each item option has a `metadata` object, so the object could just store metadata for a single option type instead of multiple option types. The purple autumn tee can be modeled as
```typescript
{
  name: 'Purple Autumn Tee',
  ...,
  options: [
    {
      ...,
      metadata: {
        type: 'SIZE',
        value: 'S',
        position: 1,
      }
    }, {
      ...,
      metadata: {
        type: 'SIZE',
        value: 'M',
        position: 2,
      }
    }, {
      ...,
      metadata: {
        type: 'SIZE',
        value: 'L',
        position: 3,
      }
    }
  ]
}
```

The BE can verify that there's either one option with no metadata or all options have a `value` field and the same `type`. The logic for the FE would be something similar where if `options` has size 1, then no selecting from multiple options, else pull out the single `type` value (the BE guarantees all options have the same `type`) and present the options.

I see an argument for `type` belonging to the item model and I initially thought it should, but thinking about it some more, I think it makes sense to keep it in `metadata` next to `value` for context and instead of splitting the optional metadata across two tables. The FE can pull `type` out into the item for its convenience. This way we can easily deal with the single- and multiple-option cases (and leave the schema flexible enough for a grid of options if we ever decide to go down that route).

It seems much simpler for the BE to stick with the current schema and doesn't change much for the FE; with the proposed changes, I'd imagine `value` and `position` would also have to be optional for the single-option case, and if we have that many optional fields I think we've gone wrong somewhere. It seems odd that we'd have a loose `metadata` field and then enforce constraints on it (the BE check I mentioned earlier), but I think it makes more sense this way (optional `metadata` field in the item option table) than to have multiple optional fields loosely related across tables (`option type` in the item table, `value` and `position` in the item option table). Alternatively, if we want to have a more structured `metadata` field, we could have another table called `MerchItemOptionMetadata`, where that has required `type`, `value`, and `position` fields but it's optional for `MerchItemOption` to have a `MerchItemOptionMetadata`. That might be the best option since the types are all nicely laid out in our schema, but it also feels a little superfluous and possibly too strict; I think it's worth building in a little flexibility with the `metadata: object` field since the set of all possible merch isn't really well-defined.

**Comment by steets250** [comment]
The alternate structure you proposed with continuing to use the metadata field looks great. I think just updating the verification logic to ensure that there's either one item option with no metadata, or that every option has the same type is great cause it means we can assure that data gets set correctly from the frontend.

**Comment by sumeet-bansal** [comment]
We could even have a field in the item table that could be set to ‘SINGLE‘ or ‘MULTIPLE‘ but probably don't need to.

**Comment by shravanhariharan2** [comment]
After discussing a bit more with Steven about requirements, here's the new changes:
* add a `themeColor` field for `MerchItemCollection` (the color for the text will likely be reused elsewhere)
* add a boolean field (tentatively `hasVariants`) that specifies if an item has only 1 options. This is required so that if an admin tries to add more options to an item meant to have only 1 option, an error will be thrown.
* add validation for option type on item option creation and item creation to check if all the `type` fields are the same
* update the seeds to reflect the metadata/schema change

**Comment by sumeet-bansal** [comment]
Sounds good.
