### ISSUE TITLE
Write auth controller test suite

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#191]

**Comment by shravanhariharan2** [comment]
Exact tests/assertions are TODO by the assignee. @michl1001 feel free to drop your test suite design below

**Comment by michl1001** [comment]
**Design:**
login
- tests that a user can get a valid auth token from valid login
- test that a user is rejected for invalid login
register 
- tests that register gives the correct output for a new account
- tests that register throws correct error given overlapping accounts
verifyAuthToken
- valid AuthToken returns true
- invalid AuthToken returns false
verifyEmail
 - tests that a newly registered user can verify email correctly and sets user accordingly
 - tests that an already registered user does not verify twice
 - tests that invalid codes throws error
resendEmailVerification
- tests that the email is resent without error
- tests that invalid email throws error
sendPasswordResetEmail
- tests that the functions runs without error
- tests that the user state is edited appropriately
- tests that invalid email throws error
resetPassword
- tests that the functions runs without error
- tests that invalid codes throws error

WIP, let me know if there is any feedback!

**Comment by shravanhariharan2** [comment]
Overall LGTM, one thing to consider is how we should be checking if an email sends or not, since a lot of these tests deal with emails being sent. Ideally what we want is to check that the email data is correct (i.e. the sender, receiver, the subject, the template), but not actually have any email send (since we're using fake emails for testing). This can be done with mocking.

If you aren't familiar with the concept of mocking functions/classes, [this article](https://www.telerik.com/products/mocking/unit-testing.aspx#:~:text=Mocking%20is%20a%20process%20used,or%20state%20of%20external%20dependencies.) looks to be a good first read. We're going to be using [ts-mockito](https://github.com/NagRock/ts-mockito) for mocking for TypeScript (mockito being a pretty commonly used mocking library for Java). Feel free to start implementation
