### ISSUE TITLE
Add order limit to pickup events

### ISSUE THREAD

**Issue by shravanhariharan2** [acmucsd/membership-portal#208]
Pickup events should include an `orderLimit: number` field to hold the maximum number of orders to be fulfilled at the event. This will help with scheduling, so that users know that they can't select specific pickup events because they have been fully booked already.

**Comment by StormFireFox1** [comment]
This requires 4 changes:
- Add ability to create or edit order limit field
- Error order requests if pickup event would go over order limit
- Allow for field to be returned as information to admin
- Ensure admin cannot edit order limit field below current order numbers booked on pickup event

**Comment by steets250** [comment]
I think it makes sense to limit by orders. The goal here would be to prevent a large rush / queue of people coming to a pickup event and having to wait for a long time to pick up their items. There isn't much of a difference based on how many order items a person orders, since that's something that can be grouped together before pick up and just handed over during the pickup event.
