### ISSUE TITLE
Add Ability to Change Email

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#229]
Allow a user to change their account email, this should put the user back into the email verification account state.

**Comment by trulyronak** [comment]
proposal: simply use the existing verify email apparatus, and make it so that when a user changes their email, they simply have to go through initial user steps.

flow:
initial state: user is verified:

```
{
    "error": null,
    "user": {
        "uuid": "d22ee4cf-1939-4ae4-a850-7be580c82b06",
        "email": "smhariha@ucsd.edu",
        "firstName": "Shravan",
        "lastName": "Hariharan",
        "profilePicture": null,
        "accessType": "STAFF",
        "state": "ACTIVE",
        "graduationYear": 2024,
        "major": "Bioinformatics",
        "bio": null,
        "points": 55,
        "credits": 5500
    }
}
```
user w/ verified account requests to change email to `newemail@email.com`
- email verification email sent to `newemail@email.com`
- user state changes to `PENDING` (should we make a new state here?)

user model state:
```
{
    "error": null,
    "user": {
        "uuid": "d22ee4cf-1939-4ae4-a850-7be580c82b06",
        "email": "newemail@email.com",
        "firstName": "Shravan",
        "lastName": "Hariharan",
        "profilePicture": null,
        "accessType": "STAFF",
        "state": "PENDING",
        "graduationYear": 2024,
        "major": "Bioinformatics",
        "bio": null,
        "points": 55,
        "credits": 5500
    }
}
```

user clicks on verify email link, verifying their email
- calls regular verify email route for this

user model state:
```
{
    "error": null,
    "user": {
        "uuid": "d22ee4cf-1939-4ae4-a850-7be580c82b06",
        "email": "newemail@email.com",
        "firstName": "Shravan",
        "lastName": "Hariharan",
        "profilePicture": null,
        "accessType": "STAFF",
        "state": "ACTIVE",
        "graduationYear": 2024,
        "major": "Bioinformatics",
        "bio": null,
        "points": 55,
        "credits": 5500
    }
}
```

**Comment by trulyronak** [comment]
key issue (if we wanna care)
- a user changes their email to an account they don't have access to
- they get logged out / they log out, thinking they'll just verify later
- turns out they put the wrong email (typo / whatever)
- they cannot login and change the email they typed, since they cannot login
    - tho ig technically they can as long as they remember the bad email they typed
- they are stuck

**Comment by shravanhariharan2** [comment]
@steets250 feel free to comment as well, but I'm thinking we can roll with the implementation Ronak specified, and if someone gets locked out, they can just contact someone from board and that can be forwarded to dev team, where we can reset their email to whatever their old email was (we'd just ask them), reset the state to ACTIVE, and then ask them to try again. I doubt this case would come up often, so if it does, we can handle it in an on-call sort of manner vs. having functionality for rolling back email updates or something else.
