### ISSUE TITLE
GET order data updates

### ISSUE THREAD

**Issue by steets250** [acmucsd/membership-portal#235]
For the `GET /store/order/:uuid`, can it return:
```
itemName: string;
picture: string;
status: any; // Not sure what order status type is
```
as part of the `PublicOrderItem` as well? (And maybe the description as well just to cover everything). The cart display needs the photo and name to display the order summary, and I want to avoid needing to do lookups of the items to get their data.

**Comment by shravanhariharan2** [comment]
Doesn't the cart display use `GET /cart`? If so, that data should already be provided with the API. Or do you mean we'd want to return item name/description/picture info for every item in a user's order, regardless of where in the UI it's at?

**Comment by steets250** [comment]
Ah good point, we ended up just going with the implementation of storing the full item data locally, so the component didn't use `GET /cart`. I'll see if I can use that route to address the data needed to display past orders, and if so, I'll close this issue.

**Comment by shravanhariharan2** [comment]
@steets250 what're the pages in which you're using the `PublicOrderItem` objects? If we're using them in locations outside of the cart, then I;m happy to modify the data payload still, since I don't think we should be relying on a cart-specific route for non-cart-related views.

I'm thinking of adding the `MerchandiseItem` and `User` models in this route as well, so that you have all item info for each OrderItem, and all user info for displaying first name, last name, etc.

**Comment by steets250** [comment]
@shravanhariharan2 that would be awesome. There's two places where this issue is coming up. One is on the order confirmation page (or just order status page in general), where the `PublicOrderItem` doesn't provide enough information to display the list of items ordered. The other is in the admin fulfillment page, where I need the item name to display the list of what the user has ordered.

**Comment by shravanhariharan2** [comment]
Specific changes (copied from Discord):
* GET /orders - only needs join on pickup events (but join on order items can remain since lots of internal methods use that join)
* GET /order/:uuid and GET/pickup/:uuid needs order, order item, item, user, and pickup event data
