### ISSUE TITLE
Express Checkin

### ISSUE THREAD

**Issue by farisashai** [acmucsd/membership-portal#341]
If we could create a new route like `POST /checkin {email, checkinCode}`, we could add an Express Check-In feature for larger ACM events such as Kickoff to allow new users to temporarily bypass registration to get check-in points.

User Flow:
- Potential new ACM member comes to their first event and does not have a Membership Portal account yet.
  - (We require them to check in before entering and going through the full registration process would take too long and hold up the line.)
- Instead, they go to a page from the login page on the portal to submit a form with their UCSD email and checkin code for the event currently happening and get a success screen on the front-end that they have been checked in.
- On the backend, we save the event checkin data corresponding to some kind of account (not sure on the details)
  - Potential Middle Step: Email them **"Thanks for checking into your first ACM event. Here's what you can use your points for. Make sure to complete the registration process at members.acmucsd.com/register"**
- When the user later registers, they already have points on their portal account and the event attendance history.

**Comment by shravanhariharan2** [comment]
Sounds good to me - let's add an additional requirement that a user cannot express-checkin to more than 1 event. I.e., they are required to complete their full registration after the first express checkin if they want to continue earning points through attendance.

**Comment by shravanhariharan2** [comment]
Do we think it makes sense for the attendance to only count towards an event's attendance count once the user fully registers their account? I think this makes sense because otherwise, users can express-checkin many times to the same event with different emails, and that would count towards an event's attendance count.

This implementation would mean that an event's attendance count = the sum of attendances by registered users, rather than the sum of attendances by registered users + the sum of express checkins

**Comment by farisashai** [comment]
> Sounds good to me - let's add an additional requirement that a user cannot express-checkin to more than 1 event. I.e., they are required to complete their full registration after the first express checkin if they want to continue earning points through attendance.

Yeah, that's what I was thinking too. We will clarify on the front end that this page can only be used if you do not currently have an active ACM account so it would help if we could send an error after a successful submission on this page as a reminder to the user to complete registration.

**Comment by farisashai** [comment]
> Do we think it makes sense for the attendance to only count towards an event's attendance count once the user fully registers their account? I think this makes sense because otherwise, users can express-checkin many times to the same event with different emails, and that would count towards an event's attendance count.
> 
> This implementation would mean that an event's attendance count = the sum of attendances by registered users, rather than the sum of attendances by registered users + the sum of express checkins

I don't see a reason why any user would do that but it might be a good safety check regardless. My main example while developing this feature is specifically a Kickoff scale event with an extremely long line so I wonder if it would undervalue the attendees on Metabase maybe or if the registration aspect updating the event attendees is sufficient to handle that concern.

**Comment by farisashai** [comment]
Haven't checked the code yet but these are the possible errors and logic flows I can foresee

## Form (email, checkinCode)

### Error Flows
- Empty email: "No email provided"
- Invalid email format: "Invalid email"
- Already existing email on Portal: "This email is already registered to an ACM account. Please log in to check in to this event."

- Empty Check In Code: "No checkin code provided.
- Invalid Check In Code: "Invalid check in code".
- Invalid Check In Time: "This event has not started yet/ this event has already finished"

- Valid Form Submission that has already checked in: "This email has already been checked in for this event!"

### Successful Flow
- Valid Email for Non-existent user + valid checkin code for live event: "Successfully checked in!" -> Send Email -> UI takes them to a page "Thank you for checking in!"

**Comment by shravanhariharan2** [comment]
> Haven't checked the code yet but these are the possible errors and logic flows I can foresee

Yep these should all be covered by the code already.

> I don't see a reason why any user would do that but it might be a good safety check regardless.

Yeah the main point of this from a business logic standpoint would be to prevent users from inflating event attendance intentionally (which yes in reality I hope no one does this, but theoretically it is possible to do so so we should have a way to handle this).

Additionally from an engineering design standpoint, not adding to the attendances table until registration/verification is complete reduces the blast radius (i.e. database storage costs in this case) of malicious users who may look to spam this route or do what I mentioned above. I'm planning on implementing some rate-limiting for this route too to make sure it doesn't get spammed, since it's the first non-authenticated route we are exposing that has an associated cost to it (emails being sent).

**Comment by dowhep** [comment]
This is implemented already right?
